### ISSUE TITLE
Empty Search

### ISSUE THREAD

**Issue by spy0012** [uaktags/explorer#11]
I have noticed if you press search with nothing in the box you get a page isn't working and the address bar showing

/block/[object%20Object]
Normally it would show an error text saying no results found i am assuming this from translation should kick in error": "Error! - {{error}}
Unmodified explorer is - "ex_search_error": "Search found no results for: ",

**Comment by uaktags** [comment]
Presumably this is an issue in https://github.com/uaktags/explorer/blob/master/routes/index.js starting at line 303. I'll take a look later and see what I see.

**Comment by spy0012** [comment]
Looks like Dstra never got this working either, checked the code and matches, and fails as such too, but all explorers in .jade work fine

**Comment by uaktags** [comment]
Yea, i doubt its with pug/jade, just something in the backend not being handled properly. I'm a little swamped today but i'll get to it in the next 3-4hours.

**Comment by uaktags** [comment]
Found some extra time. Give that a gander and see if that resolves it for you!

**Comment by spy0012** [comment]
![image](https://user-images.githubusercontent.com/10012503/56919105-a61d2c80-6ab7-11e9-8836-c321950f5859.png)

Great it works, thank you hoping i am not rushing you as i know you are doing the explorer at your own pace and don't want to take you away from other work.

Appreciate the fixes

**Comment by uaktags** [comment]
No worries. I may soon adapt that message for when it's empty to say it's empty, but it should work if you put in a string and say "Search found no results: alsdfkjaldkfj".
