### ISSUE TITLE
Coininfo

### ISSUE THREAD

**Issue by spy0012** [uaktags/explorer#12]
Coininfo is missing from settings.json - i have added the setting true or false but i think i am missing something for it to show the page

`/var/www/vhosts/explorer/views/coininfo.pug:31 29| h5.sub=t('coininfo.coin_supply') 30| .row.info-row > 31| if settings.coininfo.masternodes.enabled 32| .col-md-4 33| h4 #{totalMasternodes} 34| h5.sub=t('coininfo.total_nodes') Cannot read property 'enabled' of undefined`

I don't think app.js looks for a toggle or index i will look at previous explorer i used to see if that is the case.

Sorry to keep adding issues, i am trying to fix these i was okay with jade but a lot of things changed and i haven't quite caught up.

**Comment by uaktags** [comment]
```
i am trying to fix these i was okay with jade but a lot of things changed and i haven't quite caught up.
```
Yea that's the same issue I'm having. Quite a few things have changed since pug evolved.

I'll take a look at the missing variable in settings.json.template. I believe one of my test servers has this working in it.

**Comment by uaktags** [comment]
Give that a try, let me know if that helps. Looks like I didn't update the template:

```
  // Coin info page
  "coininfo": {
    "basic_info_links": [
      ["Github", "http://github.com/"]
    ],
    "masternodes":{
      "enabled": true,
      "deposit_required": 50000
    },
    "block_time_sec": 120,
    "block_reward_mn": 5
  },
```

**Comment by spy0012** [comment]
Great the page loads as it should but because of issue #10 data is not inserted, but it fixes the viewing of the page :) However it doesn't show required coins value "deposit_required": i am assuming that isn't because the the masternode details are not pulling

**Comment by uaktags** [comment]
Nope, its not showing because variables have changed. fix incoming to just pull from settings.

**Comment by uaktags** [comment]
For what its worth, in regards to coininfo, it's largely based off of another repo (probably Sigwo or Masterhash). However, they were very specific to their respected coins (atleast sigwo was, i've never seen masterhash because they deleted their repo).
So alot of coininfo is uncommented out, which you can see by going to routes/index.js and going to line 130. Alot of that functionality is still to be brought in with better integration of the Coin markets.

**Comment by spy0012** [comment]
I was looking in the wrong area for that setting lol, thanks

Yes the previous explorer had estimated earnings and i am sure they were incorrect roi but never really looked into it

**Comment by spy0012** [comment]
Just a quick one regarding locked coins don’t show on coininfo, I am assuming it’s a command missing

**Comment by spy0012** [comment]
Thanks, i was looking at the wrong option - Great work

**Comment by spy0012** [comment]
Another thing i have noticed any links added to coin info get this appended a link like below and not the actual link, i will look at coininfo.pug i think its template related.

explorerurl/coininfo#{item[1]} instead of github link.

Unrelated and i tried to get this to work maybe i just don't how to parse settings but how would i add further headers to this section

![image](https://user-images.githubusercontent.com/10012503/57005950-449eb000-6bd4-11e9-9ca3-b4f4f5f0ad3a.png)

So say after basic info i wanted another header saying Exchanges so we would have Basic info > links
Exchanges > links

**Comment by uaktags** [comment]
Alright, how about this?
```
// Coin info page
  "coininfo": {
    "basic_info_links": {
      "Overview": {
        "Github":"https://github.com/ripple/rippled"
      },
      "Exchanges": {
        "HitBTC": "https://hitbtc.com/XRP-to-BTC",
        "Binance": "https://www.binance.com/en/trade/XRP_BTC"
      },
      "Misc": {
        "CoinGecko": "https://www.coingecko.com/en/coins/ripple#panel"
      }
    },
```
![choice1](https://user-images.githubusercontent.com/893684/57029710-84838880-6c10-11e9-8a92-5af2c3e13b89.png)

Basically, I wouldn't care what you put in here and it can be anything you want:
```
// Coin info page
  "coininfo": {
    "basic_info_links": {
      "Coin Website": {
        "Github":"https://github.com/ripple/rippled"
      },
      "Social Netowrk": {
        "Github": "https://hitbtc.com/XRP-to-BTC",
        "Google+": "REST-IN-PEACE"
      },
      "RickJames": {
        "I'm": "Rick James.....(.com)"
      },
"More": {
        "Is": "better.com"
      },
    },
```

**Comment by uaktags** [comment]
Or are you looking for additional cards?
![2019-05-01 13_04_34-Vulc](https://user-images.githubusercontent.com/893684/57030110-b9440f80-6c11-11e9-84e0-78decd73afc6.png)

**Comment by uaktags** [comment]
If this is what you're looking for, then I'll push an update for it. I'll try to leave backward compatibility for anyone that has the old way, but I do agree having a few more links would look nicer.

**Comment by spy0012** [comment]
I like the last one
https://github.com/uaktags/explorer/issues/12#issuecomment-488343776

Looks more organised

**Comment by uaktags** [comment]
Great, I'll start working on the backward compat and new settings structure for this.

**Comment by uaktags** [comment]
```
// Coin info page
  "coininfo": {
    "basic_info_links": [
      ["Github", "http://github.com/"]
    ],
    "use_enhanced_info_links": false,
    "enhanced_info_links": {
      "Overview": {
        "Github":"https://github.com/"
      },
      "Exchanges": {
        "HitBTC": "https://hitbtc.com/",
        "Binance": "https://www.binance.com/"
      },
      "Misc": {
        "CoinGecko": "https://www.coingecko.com/en/coins/"
      }
    },
    "masternodes":{
      "enabled": false,
      "deposit_required": 50000
    },
    "block_time_sec": 120,
    "block_reward_mn": 5
  },
```
so modify the enhanced_info_links as needed, set the "use_enhanced_info_links" to true, and you're good to go.

![2019-05-01 20_38_15-Vulc](https://user-images.githubusercontent.com/893684/57051765-14492700-6c51-11e9-8ae3-1588c634a971.png)

By default, it's set to false so that backward compatibility is left in place for anyone still testing.

**Comment by uaktags** [comment]
With that, I'm closing this issue. We can open new issues that are more to the point of what is needed.
