### ISSUE TITLE
-Cosmetic - Movement Page Display of results

### ISSUE THREAD

**Issue by spy0012** [uaktags/explorer#15]
Just noticed on movement page, the result header is missing Tx-Id so the results are all shifted left

I removed https://github.com/uaktags/explorer/blob/8f18b9930e0aa54bb776e906a43289b10dfbafef/views/movement.pug#L68-L73

and added
```
 .col-xs-12.col-md-12(style="margin-bottom: 5%")
      .panel.panel-default
        .panel-heading
          strong= t('movement.latest')
        table#alerts-table.table.table-bordered.table-striped
          thead
            tr
              th.text-center= t('movement.timestamp')
              th.hidden-xs.text-center= t('movement.txid')
              th.text-center= t('movement.amount_coin',{coin : settings.symbol})
          tbody.text-center
  .footer-padding
```
Not sure if your code is intentional or not just thought i would mention it, spacing and tables match all other pages except network gonna look at that now.

When i enable lengthChange the dropdown shows but the header isn't like masternodes

![image](https://user-images.githubusercontent.com/10012503/56923464-8808f980-6ac2-11e9-9ac9-39e2e77cdd58.png)
![image](https://user-images.githubusercontent.com/10012503/56923495-99ea9c80-6ac2-11e9-9adf-49d0a08f353c.png)

First image does not have a header box like 2nd image, code could be wrong still working on it

**Comment by uaktags** [comment]
Ah, okay yep. So movement is one of those jade => pug and Bootstrap 3=>4 conversions that I never worked on fixing yet. I'll take a stab at it right now.

**Comment by spy0012** [comment]
Just tell me to go away lol if i am making work for you that you will get to at your pace

**Comment by uaktags** [comment]
Haha, I actually forgot all about this project/repo. iquidus never responded to me about making me a collaborator on his repo and the crypto market was slowing down, so this atleast brought this back to life a bit.

**Comment by uaktags** [comment]
Give that a try

**Comment by spy0012** [comment]
Yes much better than my attempt, i just needed to center labels, thanks
```
            th.text-center=t('movement.timestamp')
```

**Comment by uaktags** [comment]
Great, then I think it's safe to close this out
