### ISSUE TITLE
Don't expose the explorer to 0.0.0.0 ( Feature request )

### ISSUE THREAD

**Issue by streetcrypto7** [uaktags/explorer#32]
Hello,

For reverse proxy users like me exposing the explorer to 0.0.0.0 is not efficient.

By adding 127.0.0.1 on ```var server = app.listen(app.get('port'), function() {``` would prevent this problem.

**Comment by uaktags** [comment]
Agreed, I believe this should actually be default for "production" and perhaps expose it for dev purposes (requiring an update to how npm start is ran). Outside of that, I really don't know why anyone would fully expose node apps.
