### ISSUE TITLE
BUG: Missing information on block page

### ISSUE THREAD

**Issue by streetcrypto7** [uaktags/explorer#35]
On iquidus

![캡처](https://user-images.githubusercontent.com/52137633/60544854-a30f1880-9d54-11e9-93f6-5e557565d4e3.PNG)

On uaktags fork

![캡처2](https://user-images.githubusercontent.com/52137633/60544860-a86c6300-9d54-11e9-89bd-568aa8c9b1cd.PNG)

Hash table is missing on block page.

This is a serious issue!

**Comment by uaktags** [comment]
I wouldn't call this a "serious" issue, but definitely an annoyance. 

https://github.com/uaktags/explorer/blob/55e8a54eec5da0627e0a631778458896d767d078/views/block.pug#L89

My guess is this is another pug headache. Looking into what it doesn't like about this.

**Comment by streetcrypto7** [comment]
Can we fix?

**Comment by uaktags** [comment]
Should definitely be an easy fix, just need to check it out for what it doesn't like. Either the variable is wrong or the assignment. Nothing looking at it is jumping out.

**Comment by uaktags** [comment]
```
th.hidden-xs.d-none.d-sm-table-cell=t('explorer.hash')
              th=t('tx.recipients_address')
              th=t('address.amount_coin', {coin: settings.symbol})
              th
          tbody
            each txn in txs
              tr
                td.hidden-xs.d-none.d-sm-table-cell
```
Problem was on lines 81 and 88.

I'll push out later when i get a free moment.

**Comment by streetcrypto7** [comment]
It works however the eye part on the right is still missing

![캡처](https://user-images.githubusercontent.com/52137633/60548085-34ce5400-9d5c-11e9-8281-d22638e9a75a.PNG)

**Comment by streetcrypto7** [comment]
Information button is also misssing

![캡처2](https://user-images.githubusercontent.com/52137633/60548226-87a80b80-9d5c-11e9-8020-075acc683162.PNG)
![캡처](https://user-images.githubusercontent.com/52137633/60548231-8aa2fc00-9d5c-11e9-838a-d50de726d648.PNG)

**Comment by uaktags** [comment]
IT's on the right side?

**Comment by streetcrypto7** [comment]
Yes

**Comment by uaktags** [comment]
Gotcha I see what this was saying, definitely read it wrong. I'm thinking fa-eye-open needs to be changed to fa-eye instead. 

Inspect element and try changing that class to see if it works. Im looking at this via mobile and won't be able to test til tomorrow/weekend when I start pushing commits.
